CREATE TABLE user_info
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name      VARCHAR(255),
    call_sign VARCHAR(255),
    unit      VARCHAR(255),
    role      VARCHAR(255),
    CONSTRAINT pk_userinfo PRIMARY KEY (id)
);